from tkinter import *
from tkinter.ttk import *
root = Tk()
root.title('Pizza Steve\'s Menu')
pepperoni = Label(root, text='Pepperoni').pack(padx=12, pady=15)
supreme = Label(root, text='Supreme').pack(padx=12, pady=15)
extra = Label(root, text='Extravaganza').pack(padx=12, pady=15)
all_cheese = Label(root, text='Cheesiest').pack(padx=12, pady=15)
hawiian = Label(root, text='Hawiian').pack(padx=12, pady=15)
sausage = Label(root, text='Sausage').pack(padx=12, pady=15)
bbq = Label(root, text='BBQ Chicken').pack(padx=12, pady=15)
buffalo = Label(root, text='Buffalo Chicken').pack(padx=12, pady=15)
size = Label(root, text='***Size and Price***').pack(padx=12, pady=15)
small = Label(root, text='Small for $8.99').pack(padx=12, pady=15)
medium = Label(root, text='Medium for 10.99').pack(padx=12, pady=15)
large = Label(root, text='Large for $12.99').pack(padx=12, pady=15)
xlarge = Label(root, text='X-Large for $14.99').pack(padx=12, pady=15)
method = Label(root, text='Delivery($3.99) and Carryout!').pack(padx=12, pady=15)
order = Button(root, text='Order', command=root.destroy).pack(padx=12, pady=15)
root.mainloop()